2025-04-03 20:01:35.043668 - ðŸš€ Script started!
2025-04-03 20:01:35.046275 - ðŸ”Œ Trying to connect to Telegram...
2025-04-03 20:01:35.869262 - ðŸ”¥ Exception in main: The authorization key (session file) was used under two different IP addresses simultaneously, and can no longer be used. Use the same session exclusively, or use different sessions (caused by InvokeWithLayerRequest(InitConnectionRequest(GetConfigRequest)))
2025-04-03 20:01:35.869793 - Traceback (most recent call last):
  File "/home/vahid279/public_html/addons/academit/bot/telegram_forwarder/forwarder.py", line 31, in main
    await client.connect()
  File "/home/vahid279/virtualenv/public_html/addons/academit/bot/telegram_forwarder/3.10/lib/python3.10/site-packages/telethon/client/telegrambaseclient.py", line 598, in connect
    await self._sender.send(functions.InvokeWithLayerRequest(LAYER, req))
telethon.errors.rpcerrorlist.AuthKeyDuplicatedError: The authorization key (session file) was used under two different IP addresses simultaneously, and can no longer be used. Use the same session exclusively, or use different sessions (caused by InvokeWithLayerRequest(InitConnectionRequest(GetConfigRequest)))

2025-04-03 20:02:04.750031 - ðŸš€ Script started!
2025-04-03 20:02:04.751758 - ðŸ”Œ Trying to connect to Telegram...
2025-04-03 20:02:05.551738 - ðŸ”¥ Exception in main: The authorization key (session file) was used under two different IP addresses simultaneously, and can no longer be used. Use the same session exclusively, or use different sessions (caused by InvokeWithLayerRequest(InitConnectionRequest(GetConfigRequest)))
2025-04-03 20:02:05.552439 - Traceback (most recent call last):
  File "/home/vahid279/public_html/addons/academit/bot/telegram_forwarder/forwarder.py", line 31, in main
    await client.connect()
  File "/home/vahid279/virtualenv/public_html/addons/academit/bot/telegram_forwarder/3.10/lib/python3.10/site-packages/telethon/client/telegrambaseclient.py", line 598, in connect
    await self._sender.send(functions.InvokeWithLayerRequest(LAYER, req))
telethon.errors.rpcerrorlist.AuthKeyDuplicatedError: The authorization key (session file) was used under two different IP addresses simultaneously, and can no longer be used. Use the same session exclusively, or use different sessions (caused by InvokeWithLayerRequest(InitConnectionRequest(GetConfigRequest)))

2025-04-03 20:03:25.626988 - ðŸš€ Script started!
2025-04-03 20:03:25.628526 - ðŸ”Œ Trying to connect to Telegram...
2025-04-03 20:03:26.421187 - ðŸ”¥ Exception in main: The authorization key (session file) was used under two different IP addresses simultaneously, and can no longer be used. Use the same session exclusively, or use different sessions (caused by InvokeWithLayerRequest(InitConnectionRequest(GetConfigRequest)))
2025-04-03 20:03:26.421674 - Traceback (most recent call last):
  File "/home/vahid279/public_html/addons/academit/bot/telegram_forwarder/forwarder.py", line 31, in main
    await client.connect()
  File "/home/vahid279/virtualenv/public_html/addons/academit/bot/telegram_forwarder/3.10/lib/python3.10/site-packages/telethon/client/telegrambaseclient.py", line 541, in connect
    await self._sender.send(functions.InvokeWithLayerRequest(
telethon.errors.rpcerrorlist.AuthKeyDuplicatedError: The authorization key (session file) was used under two different IP addresses simultaneously, and can no longer be used. Use the same session exclusively, or use different sessions (caused by InvokeWithLayerRequest(InitConnectionRequest(GetConfigRequest)))

